name: Cloudflare Deploy
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  push:
    branches: [ "testaction" ]
  pull_request:
    branches: [ "testaction" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.5.0]  # æ›´æ–°ä¸ºä½ æƒ³è¦ä½¿ç”¨çš„ Node.js ç‰ˆæœ¬

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Deploy to Cloudflare Workers
        env:
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TOKEN_VALUE: ${{ secrets.TOKEN_VALUE || '123456' }}
        run: |
          npm install -g wrangler
          echo "$TOKEN_VALUE" | npx wrangler secret put TOKEN --api-token $CF_API_TOKEN
          npm run deploy

